### ISSUE TITLE
Could not find a way to display pictures into radio-thumbnails selectors

### ISSUE THREAD

**Issue by alexisheloir** [pledra/odoo-product-configurator#107]
Impacted versions: at least v.9, probably all

Steps to reproduce: Not relevant

Current behavior: I want my user to display pictures for extra options, exactly the same way it is presented in the demonstration video (see screenshot) but could not figure out why.

Expected behavior: The procedure is explained somewhere in a clear and nonambiguous manner. A test database vor odoo v.9 is available as an example.

Video/Screenshot link (optional): I try have pictures in the radio thumbnails selectors like in the screenshot obtained from your teasing video without any sucess. 
<img width="532" alt="screen shot 2017-06-08 at 09 20 50" src="https://user-images.githubusercontent.com/2065032/26916788-efc366b2-4c2b-11e7-9303-3888d9aa9c0e.png">

**Comment by gam-ragnar** [comment]
I have not used odoo in a long time and this set of modules is why I'm back. Possible to have a more detailed explaination or video showing how to referencing attributes/variants to products? Thanks for this really useful module

**Comment by PCatinean** [comment]
@timfam I'm happy you find them useful. Here is a link to the documentation https://www.pledra.com/odoo-product-configurator/documentation/.

While not complete it should offer an insight.

The short story is that for the current version (there will be an update in the future) you need to set the images on regular product variants and link the attribute value to the variant.

The price and image will both be used from the related product.

@alexisheloir sorry for the huge delay I got sidetracked completely.

**Comment by andreampiovesana** [comment]
You have to set price and image to the product the link the product in the
attribute value table.
Ok?

Il 08/giu/2017 09:22, "alexisheloir" <notifications@github.com> ha scritto:
