### ISSUE TITLE
is it necessary to set "domain=[('config_ok', '=', False)]" for product_id  in sale.order.line and stock.move?

### ISSUE THREAD

**Issue by qq470647251** [pledra/odoo-product-configurator#114]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by PCatinean** [comment]
@qq470647251 if that domain is removed then all possible variants will be shown. One cannot easily select the variant this way and you would have a huge list of variants that will flood the selection list.

The wizard is used for both creating variants as well as identifying and adding them.

**Comment by qq470647251** [comment]
@PCatinean thanks for your answer.but i think it's more  directly by using the internal search view.

**Comment by PCatinean** [comment]
@qq470647251 true that is possible, though how will you search by attribute values?
