### ISSUE TITLE
v10 website_product_configurator price formatt not correct

### ISSUE THREAD

**Issue by brokemeisteratwork** [pledra/odoo-product-configurator#12]
Hi,

while configuring a product in the frontend the price has the wrong format:

30,9 EUR => 30,90 EUR

If you select an optionen (no price change):
30,9000000000002 EUR => 30,90 EUR

![prodconf_issue1](https://cloud.githubusercontent.com/assets/2691301/21924083/c5f02bbc-d977-11e6-95c8-3b9a79277ee7.PNG)

![prodconf_issue2](https://cloud.githubusercontent.com/assets/2691301/21924082/c5ee5f6c-d977-11e6-94ad-3e84983e12e4.PNG)

Cheers,

Malte

**Comment by PCatinean** [comment]
@brokemeisteratwork thank you for reporting the bug.
This should now be fixed by ccd6dc66e192f8011eb5c9603c1c94accb73f151
It should also take into account the language and currency settings.

Please confirm so I may close the issue.

**Comment by brokemeisteratwork** [comment]
If you selection one attribute the price format is correct.

But if your entering each of one step ore more step the intial price of the step is not formatted. It's still e.g. "30.9"

**Comment by PCatinean** [comment]
@brokemeisteratwork did you update the module after pulling the latest updates?

Can you provide a more detailed step-by-step list of instructions to reproduce the error?

I went through all the steps and added options then clicked on each step separately and I get the same result

**Comment by PCatinean** [comment]
@brokemeisteratwork if you have used the website editor previous to the decimal fix, the view is frozen with noupdate=True.

Please make sure the website_product_configurator.product_configurator view has this line
`<t t-set="prices" t-value="product_tmpl.get_cfg_price(cfg_val_ids.ids, **formatLang=True**)"/>`

with the extra kwarg formatLang="True"

**Comment by PCatinean** [comment]
I will again close the issue until further notice. If it's still not solved please feel free to reopen it.
