### ISSUE TITLE
[10.0] Refactor to have the same design as Magento bundle

### ISSUE THREAD

**Issue by max3903** [pledra/odoo-product-configurator#122]
Hello @PCatinean 

We have been contracted to make some customizations to the product configurator. The customer is currently using Odoo 8 and Magento bundles and would like to migrate to Odoo 10 and the product configurator.

The problem is that Magento allows to have various information on the relationship between an attribute line and an attribute value: default value checkbox, user defined quantity, default quantity, maximum quantity.

See screenshot here:
https://i.ytimg.com/vi/_yCbxbcCUCM/maxresdefault.jpg

We would like to refactor the Odoo product configurator to have the same design and allow information on attribute value in a specific product attribute line.

What do you think? Would you accept to review our pull request for this?

**Comment by PCatinean** [comment]
Hi @max3903 I'm not sure I got this right, but the examples you gave me there are already on the product.attribute.line. If you are referring to these new fields in relation with each and every attr-line / attr-value relationship then I think it's too specific. It would get increasingly complex and loose the generic aspect imo. It sounds more like a mangeto-specific fork than a general improvement.

I still have in plan a greater refactoring to put everything together in a different way which would change things a bit. I plan to launch it with v11 and backport what's possible to v10 and v9.

This is the reason I stopped reviews at PR's for the time being.

**Comment by max3903** [comment]
Hi @PCatinean

Can I ask you to reconsider as we managed to keep the compability with your current design:
https://github.com/ursais/odoo-product-configurator/tree/10.0-lsp

**Comment by PCatinean** [comment]
@max3903 if the magento-related functionality can be contained in a completely separated module that's independent for the base one then that is indeed an improvement and of course more than welcome.

Having it in the base modules for someone that does not use magento or changing the main structure heavily just to accommodate that would be an issue imo.

What do you think?

**Comment by max3903** [comment]
@PCatinean We made some changes to your modules and didn't keep everything we did in a separate module.
