### ISSUE TITLE
Attribute Name in the Quotation / Sales Order Description

### ISSUE THREAD

**Issue by Ronny-Lintermans** [pledra/odoo-product-configurator#128]
Impacted versions:10 EE

Steps to reproduce: Configure Product in Web front end en create a Quotation of it

Current behavior:After Configuration the web view presents all the configured attributes listed with format "attribute name : attribute value". In quotation description you only get the attribute values which is not clear

Expected behavior: In quotation and Sales Orders mention in the product description "attribute name : attribute value"

Video/Screenshot link (optional):

**Comment by PCatinean** [comment]
This is also related to https://github.com/pledra/odoo-product-configurator/issues/132 in my opinion as it's also about what to include in the description and how to form the description.
