### ISSUE TITLE
Don't show the zero price in Web Configurator

### ISSUE THREAD

**Issue by Ronny-Lintermans** [pledra/odoo-product-configurator#131]
Impacted versions:10 EE

Steps to reproduce:Config Template with attribute Chassis and two values Opel & Renault.
Herewith two products are coupled having a Picture and zero price.

Current behavior:In Web view radio-thumbnail the two products are shown with their picture and price underneath of 0.00€

Expected behavior: Leave the zero prices away, hide the zero prices
![web config zero prices](https://user-images.githubusercontent.com/32063581/30801650-3c1fc8d0-a1e4-11e7-8b74-c9786be2d9eb.JPG)

Video/Screenshot link (optional):

**Comment by andreampiovesana** [comment]
i need the same ...

Andrea Piovesana linux counter #601470 ubuntu 16.04.3 + cinnamonwww.pnlug.it


2017-09-25 11:26 GMT+02:00 Ronny Lintermans <notifications@github.com>:

**Comment by PCatinean** [comment]
Fixed by https://github.com/pledra/odoo-product-configurator/pull/134
