### ISSUE TITLE
Custom Values attributes are  not shown on the Quotation / Sales Order

### ISSUE THREAD

**Issue by Ronny-Lintermans** [pledra/odoo-product-configurator#132]
![configurator comments 3](https://user-images.githubusercontent.com/32063581/31005330-7e148778-a4f8-11e7-9747-8791c0896e34.JPG)

![configurator comments 2](https://user-images.githubusercontent.com/32063581/31005327-7a070e8a-a4f8-11e7-8ec5-e793a7403dce.JPG)
Impacted versions: 10 EE

Steps to reproduce: Define an attribute that 's not required and has only custom char values, for instance "Comment" as in screen picts

Current behavior:What you fill in this Comment attribute is shown at the end of Configuration step, but is not shown in the Quotation although it's necessary for clarification.

Expected behavior: also show this Custom Value attribute, in my example the Comments typed in.
![configurator comments](https://user-images.githubusercontent.com/32063581/31005323-75a7cc58-a4f8-11e7-9635-b2acb3003982.JPG)

Video/Screenshot link (optional):

**Comment by andreampiovesana** [comment]
I need this too
Paul thanks in advance

Andrea Piovesana linux counter #601470 ubuntu 16.04.3 + cinnamonwww.pnlug.it


---------- Forwarded message ----------

**Comment by PCatinean** [comment]
It's true that the custom values do not show up on the sale.order.line description and subsequently on the report printout. While this is indeed a problem the way the problem is solved requires some extra development not just simply adding the custom values inside.

There could be a lot of cases where there are multiple custom values and throwing them all inside the order line description would cause a problem. The user needs control over the printout form and this is planned for the next version.

In the meantime I can make a quick custom module for solving your issue and send it over so you can proceed with your current deployment.

**Comment by andreampiovesana** [comment]
send it also to me
thanks

Andrea Piovesana linux counter #601470 ubuntu 16.04.3 + cinnamonwww.pnlug.it


2017-10-15 11:11 GMT+02:00 Paul Catinean <notifications@github.com>:

**Comment by Ronny-Lintermans** [comment]
Hello Paul,

This would be great if you could make us (in the meantime) a module so that we can get along with the customer’s project.

Let us know when….

Regards,
Ronny Lintermans

Van: Paul Catinean [mailto:notifications@github.com]
Verzonden: zondag 15 oktober 2017 11:12
Aan: pledra/odoo-product-configurator <odoo-product-configurator@noreply.github.com>
CC: Ronny Lintermans <ronny@dcbo.be>; Author <author@noreply.github.com>
Onderwerp: Re: [pledra/odoo-product-configurator] Custom Values attributes are not shown on the Quotation / Sales Order (#132)


It's true that the custom values do not show up on the sale.order.line description and subsequently on the report printout. While this is indeed a problem the way the problem is solved requires some extra development not just simply adding the custom values inside.

There could be a lot of cases where there are multiple custom values and throwing them all inside the order line description would cause a problem. The user needs control over the printout form and this is planned for the next version.

In the meantime I can make a quick custom module for solving your issue and send it over so you can proceed with your current deployment.

**Comment by hngo69** [comment]
Hi Paul,

Would like to request this too if the module is available.

Thanks,

Harv
