### ISSUE TITLE
Odoo 11?

### ISSUE THREAD

**Issue by MoneyJohnE** [pledra/odoo-product-configurator#138]
Impacted versions:
Would this work in Version 11?

Thanks

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by codeagencybe** [comment]
I have same question. Is this compatible with Odoo 11.0 or is there a new version available soon?

**Comment by PCatinean** [comment]
Hello,  the module is scheduled for migration and improvement later this year.
