### ISSUE TITLE
odoo-product-configurator v11

### ISSUE THREAD

**Issue by CasVissers-360ERP** [pledra/odoo-product-configurator#141]
Hi,

Are there plans to migrate the modules to Odoo v11?

Thank you for your answer.

Cas

**Comment by buzzy3** [comment]
I would contribute some funds for it, to make it quick happen, to lift this project up. From my tiny desk not a big load to get this done

**Comment by andreampiovesana** [comment]
me too

Andrea Piovesana linux counter #601470 ubuntu 16.04.3 + cinnamonwww.pnlug.it


2018-03-08 18:44 GMT+01:00 buzzy3 <notifications@github.com>:

**Comment by bsurfing** [comment]
me three, can't wait to test this in V11.

**Comment by PCatinean** [comment]
Hi everyone and thanks for the interest on the module for V11. There was another issue for this that was closed so I will leave this one open.

We've already done a small part of the migration and planning to setup an account or some form of fundraising to finance the rest of the operation.

Migration also includes refactoring and some fixes/upgrades from previous version. I will keep you posted.

**Comment by buzzy3** [comment]
Thanks for your Update, I think to lift it up to v11 its not so an big task beside of flavour. Logic does not much differ than before in Version 10.. We are going live with migration on enterprise 11 in about 2 weeks. Would be great get this "missing Piece of Puzzle" in Odoo on v11.

**Comment by PCatinean** [comment]
Migration to the next version includes server-side as well as client-side changes but we also need to complete a refactoring that was long overdue as well. That part cannot be rushed or move very quickly, especially with low financing.

**Comment by buzzy3** [comment]
start a fundraising and ask Fabien to donate. For Every Euro he donates, I pay the 0.25, because I am poor :-) Your work should become a default feature in Odoo Ent

**Comment by CasVissers-360ERP** [comment]
We are working on a basic migration of the modules (no improvements):

- product_configurator
- product_configurator_mrp
- product_configurator_wizard

I hope we can create a pull request soon.

**Comment by sum1201** [comment]
I think there should be a donation channel to facilitate donations and fund development.
Is this module accessible to OCA?
I hope this module will advance along with the new version of Odoo.
Thank you very much for providing such a great feature.

**Comment by bsurfing** [comment]
A cryptocurrency donation channel would be great!

**Comment by sum1201** [comment]
@CasVissers
I have upgraded the module to 11 and fixed some bugs.
Can I update the code to your github?  

- product_configurator
- product_configurator_mrp
- product_configurator_wizard

**Comment by PCatinean** [comment]
Thank you all for your contributions, I do have to note once more that the next version of the configurator also has been refactored and changed the structure slightly. Thus migrated code might be used but it will not be merged directly into the main branch.

**Comment by raycollazo** [comment]
@CasVissers can you contact me regarding your work on the upgrade until now. I'm not sure how much they are trying to raise here, but I have seen no movement and we have also done some work to do upgrade as well. I will gladly pay you for the modules you have upgraded thus far.
I have tried to contact pledra independently to pay for an upgrade and have gotten no response for over 2 months

**Comment by raycollazo** [comment]
@PCatinean please feel free to contact me about your financing situation, I have tried through website to communicate with someone about getting this moving.

**Comment by PCatinean** [comment]
@raycollazo sorry about that it seems the contact form got broken in the migration and I did not get around to fixing it. Please email contact@pledra.com

**Comment by PCatinean** [comment]
Fixed contact form in the meantime btw

**Comment by max3903** [comment]
@PCatinean We at @ursais are interested as well. My colleague Patrick is going to email you.

**Comment by CasVissers-360ERP** [comment]
Please see #148 for a first go at migration to v11.

**Comment by CasVissers-360ERP** [comment]
@PCatinean I see the v11 branch is created, any idea when the (betá) new modules will be pushed?

**Comment by ticktronaut** [comment]
Are there any updates on pledra product configurator on Odoo v11?

**Comment by PCatinean** [comment]
Hello everyone and thank you for the interest in the modules. We have migrated and refactored all the backend modules except MRP which we are working on right now.

After that the website modules will follow and some other extras.

We have at the moment a customer funding part of the efforts but we still have more to cover the budget.

You can btw test the latest changes on our runbot v11 branch: https://runbot.pledra.com.

Consider donating or contacting us for other funding options (invoice / pre-release etc) in order to get this out the door sooner.

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RZHQEDQW7Q8JS)

Regards,
Paul

**Comment by andreampiovesana** [comment]
alse who found v10?

Andrea Piovesana linux counter #601470 ubuntu 16.04.3 + cinnamonwww.pnlug.it



Il giorno mer 10 ott 2018 alle ore 16:11 Paul Catinean <
notifications@github.com> ha scritto:

**Comment by overdrive69** [comment]
Hi all,
what is the actuelle status of migrate web configurator to V11?

regards
over

**Comment by kirankantesariya** [comment]
Hello to All,

Yes i have Developed this Product Configuration for v11 CE and EE Compatible.
 
For Sales Quotation,Sales Order , Website Product Configuration.

For more you can Drop mail to kiran.backup0412@gmail.com

Thanks.
