### ISSUE TITLE
Dynamic domains do not survive view switches in the wizard

### ISSUE THREAD

**Issue by eric-christensen-noviat** [pledra/odoo-product-configurator#145]
Impacted versions: V10

Steps to reproduce:
I created a simple car with en engine, seat texture (leather or cloth) and seat heating. 
The seat heating depends on the type of seat texture chosen, it is only available when leather was chosen. At that point in time the user has the choice between Y/N, in case of cloth the only selection is 'N/A'.

So my restriction is: seat heating, options Y,N when seat texture is Leather.

From analysis I see when the texture is changed the dynamic domain for the seat heating gets adjusted with the correct values. But as soon as you push 'Next', the domain seems to be lost because the selection list on the heating is empty.

By putting a dummy field on the screen and then provoking an onchange event, the dynamic domains get reestablished and everything is as I expected it.

Current behavior:
see above

Expected behavior:
Dynamic domains should remain available, although I understand that this is more the responsability of the framework. The trick is rather how can we make that the domains reamin available all the way. I juggled around with a number of approoaches, but very little luck.

Video/Screenshot link (optional):

**Comment by PCatinean** [comment]
Hi @eric-christensen-noviat, I have also started noticing this issue lately and I think it's something related to changes in the upstream of the stable version.

From what I can gather this is a sort of caching issue. For example in the first two steps the fields_view_get and fields_get is called, on the third step however they are no longer called and the domains are no longer applied.

I'm also perplexed by this and have to dive in deep to fix this issue. Please let me know if you find anything in the meantime.

**Comment by PCatinean** [comment]
Fixed by https://github.com/pledra/odoo-product-configurator/pull/146
