### ISSUE TITLE
Restrictions: Or operator missing

### ISSUE THREAD

**Issue by FredrikLjungman** [pledra/odoo-product-configurator#17]
Hi
When configuring restrictions, I am missing the operator "or" as seen in the pledra documentation.
regards
Fredrik

![restrictions](https://cloud.githubusercontent.com/assets/25381253/22362252/981f5448-e461-11e6-96c9-97fa53e2fb30.JPG)

**Comment by matt454357** [comment]
I can see that this is not yet implemented.  Maybe @PCatinean would take a moment to comment on the difficulty of adding this feature.  I studied the code, and made a brief attempt, but stalled at the value_available() method.

```python
    # TODO: Refactor so multiple values can be checked at once
    # also a better method for building the domain using the logical
    # operators is required
    @api.multi
    def value_available(self, attr_val_id, value_ids):
        """Determines whether the attr_value from the product_template
            is available for selection given the configuration ids and the
            dependencies set on the product template

            :param attr_val_id: int of product.attribute.value object
            :param value_ids: list of attribute value ids

            :returns: True or False representing availability
        """
```

I can't think of a way to work around this missing feature, in my application, so I will continue to experiment on the problem.

**Comment by matt454357** [comment]
I made a pull request here: #69 
It needs testing

**Comment by PCatinean** [comment]
Your PR solved the issue and it has been merged in V9 and V10, thank you for reporting and fixing @matt454357
