### ISSUE TITLE
Hide Attribute 12 CE

### ISSUE THREAD

**Issue by elvise** [pledra/odoo-product-configurator#173]
Hi at all!
There is any way for hide attribute (not the value, but attribute) with dependency with another attribute value ?

Let me explain:
I have attribute “Do you want use weight ?” (Yes/No)
If yes show attribute field otherwise it is hidden. 

Regards

**Comment by elvise** [comment]
@PCatinean do you have any idea :) ?

**Comment by PCatinean** [comment]
@elvise this is a small improvement we wanted to add for some time. Will ask my guys to open a PR for this that you can test

**Comment by elvise** [comment]
> @elvise this is a small improvement we wanted to add for some time. Will ask my guys to open a PR for this that you can test

@PCatinean great news! :)

**Comment by elvise** [comment]
> @elvise this is a small improvement we wanted to add for some time. Will ask my guys to open a PR for this that you can test

@PCatinean Do you have any idea about ETA ?

**Comment by PCatinean** [comment]
Hoping end of the week, next Monday at latest since there are a lot of projects to handle but we'll do our best to speed it up.

**Comment by elvise** [comment]
> Hoping end of the week, next Monday at latest since there are a lot of projects to handle but we'll do our best to speed it up.

Hi @PCatinean any good news for team ? :)

**Comment by PCatinean** [comment]
@elvise it seems I have fallen back with merging a few fixes as well so everything is in https://github.com/pledra/odoo-product-configurator/pull/174/. Let me know if you have a bit of time to test the features and let me know if everything is in order.

**Comment by elvise** [comment]
> @elvise it seems I have fallen back with merging a few fixes as well so everything is in #174. Let me know if you have a bit of time to test the features and let me know if everything is in order.

Hi @PCatinean tomorrow morning as the first thing!
Please let me know what is the workflow, so i will test correctly ✌️

**Comment by elvise** [comment]
Hi @PCatinean i did some test (V12 CE):
admin side there is to fix the label, as now the field is hidden but the label remains visible:
https://recordit.co/S3LiCYoEmx

the website side seems to be working properly:
https://recordit.co/aLhUHi64m7

**Comment by PCatinean** [comment]
Thanks for the feedback! This was mostly a change for the website as the backend still uses the standard Odoo views (instead of Qweb) which is more of a headache to maintain. As the backend is more for internal users the website has focus on UI I think it's nort worth pursuing this too hard. 

If everything is in order according to you then I can merge this to stable branch.

**Comment by PCatinean** [comment]
Nvm the fix has already been submitted, can you give it another try?

**Comment by elvise** [comment]
> Nvm the fix has already been submitted, can you give it another try?

Hi @PCatinean for sure tomorrow morning as first thing ✌🏻

**Comment by elvise** [comment]
Hi @PCatinean are we sure we need this tick ?
![Schermata 2020-07-01 alle 16 09 07](https://user-images.githubusercontent.com/5269577/86253883-623f1f00-bbb5-11ea-9a5a-a418db59ca12.png)
Because from my side seems working properly from restrictions, that's correct ?

**Comment by elvise** [comment]
> Nvm the fix has already been submitted, can you give it another try?

Great job!
https://recordit.co/u3dREBSFpQ

**Comment by PCatinean** [comment]
@elvise thanks for testing! Regarding your previous question the option on the attribute serves more like a default value for the attribute lines than anything else. I get it can be confusing but it does help out when you're configuring a lot of templates.

**Comment by elvise** [comment]
> @elvise thanks for testing! Regarding your previous question the option on the attribute serves more like a default value for the attribute lines than anything else. I get it can be confusing but it does help out when you're configuring a lot of templates.

@PCatinean ok clear!
If you want add the translation for IT then:
invisible= invisibile (Italian)
