### ISSUE TITLE
Error on website after choose options

### ISSUE THREAD

**Issue by abyte20** [pledra/odoo-product-configurator#182]
Impacted versions: Odoo 13

I installed the app and tried to buy the BMW and after selecting, Engine, Body, Lines, Interior, Extras. and finally this message appears:

Error to render compiling AST
MissingError: ('Record does not exist or has been deleted. \ N (Record: product.product (83,), User: 2)', None)
Template: website_product_configurator.cfg_product
Path: / t / t [1]
Node: <t t-set = "combination_info" t-value = "product._get_combination_info (product_id = product.id, add_qty = add_qty or 1, pricelist = pricelist)" />
        

Error occurred while drawing the website_product_configurator.cfg_product template and evaluating the following expression: <t t-set = "combination_info" t-value = "product._get_combination_info (product_id = product.id, add_qty = add_qty or 1, pricelist = pricelist ) "/>

Thanks

**Comment by PCatinean** [comment]
Hi @alejandrobyte we tried to reproduce this on a new local database and were not successful. It might be that you are using a database that was initialized with an older version. Can you try on a new DB and let us know if you can still reproduce it?

**Comment by abyte20** [comment]
Hi @PCatinean 
Tested with new database and same problem :(

I installed these apps in the new database:
website (default theme)
stock
account
mrp
sale_managament
website_sale
purchase
mail
product_configurator
website_product_configurator
website_product_configurator_mrp

Thanks

**Comment by rpsjr** [comment]
I've got the same issue while creating my own data.

The problem looks to be related to use products created by **Configurable Templates** interface from Configurator app,  otherwise using base sale module to create a product and changing this product to config_ok works fine.
