### ISSUE TITLE
[9.0] Error message at installation of product configurator base

### ISSUE THREAD

**Issue by aierfino** [pledra/odoo-product-configurator#2]
I am trying to install the product configurator base module in Odoo version 9.

The following message appears before the installation is complete. 
![selection_041](https://cloud.githubusercontent.com/assets/11035376/20714248/63c2b5b2-b619-11e6-89cd-6bb48bb718ab.jpg)

**Comment by PCatinean** [comment]
@aierfino thank you for reporting! it should be fixed now
