### ISSUE TITLE
Move to next step 403 access error (if not logged in as user)

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#22]
Can you explain the reason why i get an 403 access error if i click on "Continue" button to move from one step to another to configure my custom website product before i login as regular user (anonymous user).

If i login as a regular user, i can proceed from one step to another as usual.
If i jump over the malicious step , f.e. from "step 1" to "step 3" i can proceed as expected also as a non-logged-in user.

If i login before as a regular user, i am able to "continue" as expected from one step to the next possible step without any error.

**Comment by PCatinean** [comment]
@tv-openbig I've just tried to reproduce the bug again in order to fix it but I cannot seem to replicate it.

Is is still present with the latest version of odoo and the configurator modules?

**Comment by tv-openbig** [comment]
On a fresh local system i could not recapture the issue anymore.
I am applying now minor updates also for Odoo on the staging system of the 
customer. I assume the issue could be closed.

**Comment by PCatinean** [comment]
@tv-openbig understood, feel free to re-open if you can reproduce the bug.
