### ISSUE TITLE
Adding Products to POS

### ISSUE THREAD

**Issue by jayo2005** [pledra/odoo-product-configurator#25]
Does this work with the Point of sale module? Ive added some products and they are added to the Website but not the POS even though the available in Point of Sale checkbox is checked.

**Comment by PCatinean** [comment]
No, it does not support POS as of this moment

**Comment by lukebranch** [comment]
@PCatinean ,

Just a thought, I think this may be a worthwhile feature request to consider in the long-term, although this is way out of scope of the current Odoo POS implementation. 

There is a trend (at least in Hong Kong) moving towards self-service kiosks for fast food chains (eg. McDonald's - http://www.businessinsider.com/what-self-serve-kiosks-at-mcdonalds-mean-for-cashiers-2015-8) using a simple configurator, and i've seen them popping up at restaurants of all shapes and sizes.

When I first came across your modules this concept immediately came to mind for implementing with Odoo, however I think this would require building something like this on top of the website module and then integrating it with the POS module for kitchen printers, etc.

**Comment by PCatinean** [comment]
@lukebranch that is indeed an interesting thought and I just noticed them last week at the airport.

Someone on the mailing list also suggested PoS but unfortunately that is a completely different beast.

For sure this is a nice thing for the near future but I am not too familiar with PoS and the manufacturing side is still one of the main priorities.

Nonetheless it's a good point and a good reason to move in this direction and will do so when the resources are available.

PR's, suggestions, blueprints for the feature are more than welcome.

**Comment by lukebranch** [comment]
@PCatinean ,

Thanks for taking the request under consideration. I'll definitely put together a more coherent set of features/suggestions in the future, and create a PR for further discussion if possible.

**Comment by PCatinean** [comment]
That sounds great, I'll be keen to see them, cheers!
