### ISSUE TITLE
[9.0] Traceback Configurable Variants Menu

### ISSUE THREAD

**Issue by aierfino** [pledra/odoo-product-configurator#3]
When I click on the Configurable Variants menu (under Configurable products), the following traceback appears.
![selection_046](https://cloud.githubusercontent.com/assets/11035376/20720503/5e755006-b62d-11e6-929b-f270514376de.jpg)

**Comment by PCatinean** [comment]
A few last minute changes caused this, thanks for reporting should be fixed now
