### ISSUE TITLE
[10.0] Error message when selecting variants 

### ISSUE THREAD

**Issue by aierfino** [pledra/odoo-product-configurator#4]
When creating a sales order, I can add the configured product, however at the configuration step (option to select variants) I get an error message when I select a variant. I can continue the process, however would like to know why the error message is appearing. 

![selection_107](https://cloud.githubusercontent.com/assets/11035376/21053098/e6aab34c-bdf5-11e6-994e-604fe79aa43a.jpg)

**Comment by PCatinean** [comment]
Hi @aierfino I need a bit more context to reproduce the bug.

Are you using the demo data? Can you reproduce it with demo data?

Which step to select variants are you referring to?

**Comment by PCatinean** [comment]
I just took a look through the code and saw the problem, should be fixed now.

Thank you for reporting!
