### ISSUE TITLE
configured variant is missing on sale order reports

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#6]
If i want to print sale order quotation after i have created a sale order quotation for a customer by using the "Configure Product" wizard i don't get the specifications on the report (usually in brackets).

I think it is essential to show the product with all configured variants towards the customer also on reports, in my specific use case the sale order reports.

Here is the configured product sale order line:
<img width="468" alt="bildschirmfoto 2017-01-06 um 13 30 02" src="https://cloud.githubusercontent.com/assets/8348598/21717942/6222c788-d414-11e6-9b58-c86e31f1e68d.png">

Here is the report without the selected attribute values from the "Configure Product" wizard.
<img width="365" alt="bildschirmfoto 2017-01-06 um 13 30 28" src="https://cloud.githubusercontent.com/assets/8348598/21717948/6ac35aba-d414-11e6-909d-6b7f23447adb.png">

**Comment by PCatinean** [comment]
Issue was the description of the sale order line added by the configuration wizard used the name field

There's also an problem with the description not being updated after reconfiguration but that is for another issue.

Thanks for reporting @tv-openbig !
