### ISSUE TITLE
Qweb error: unknown field "config_ok" on creation of a usual sale order

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#7]
If i want to create a sale order without using the configuration wizard to create a quotation for a usual product i get the Qweb error: unknown field "config_ok".

To reproduce the error the user needs the technical setting "Properties on lines".
Without this setting the error doesn't pop up.

<img width="1200" alt="bildschirmfoto 2017-01-12 um 12 12 19" src="https://cloud.githubusercontent.com/assets/8348598/21888761/ecf0fbea-d8c5-11e6-8bbc-47fd0210a7ab.png">

**Comment by PCatinean** [comment]
config_ok field was added only to tree view, it's now on the form view as well. Thank you for reporting!
