### ISSUE TITLE
link product to attribute value

### ISSUE THREAD

**Issue by patjo82000** [pledra/odoo-product-configurator#72]
Hi 

Can someone explain to me how to link product to attribute value in step by step in order to create dynamic price?

This is this phrase in the documentation but I dont know what it mean "As such if you want to compute an extra price for a certain attribute, create a regular product, set a price and link the product to the attribute value in the form view."

I have create the product and the attribute, but I don't know how to link the attribute value to the product

Thank you

**Comment by PCatinean** [comment]
@patjo82000 you must navigate to the product attribute form view of the product attribute value and link there the attribute.value to the product.product you created.
