### ISSUE TITLE
[10.0] Cannot select existing configurable variant in SO line

### ISSUE THREAD

**Issue by yostashiro** [pledra/odoo-product-configurator#75]
### Impacted versions:

Checked on 10.0

### Steps to reproduce:

- Create a configurable variant through configuration steps for a sales order
- Create a new sales order and try to select the configurable variant created in above step

### Current behavior:

- Cannot select the configurable variant due to `domain=[('config_ok', '=', False)]` here: https://github.com/pledra/odoo-product-configurator/blob/8a37ca77690a77e2d606110aa138b229aff31ab3/product_configurator/models/sale.py#L23
- Because of this, you are forced to go through the same configuration steps, which creates another variant with the same attributes as the existing record

### Expected behavior:

You can select an existing configurable variant in `product_id` field.

However, I am not sure why the current design applies `domain=[('config_ok', '=', False)]` to `product_id` field.  There is high chance that I'm missing some side-effects of not doing so.  Would appreciate explanation on the idea behind the design from someone more experienced with the configurator modules.

**Comment by richard-willdooit** [comment]
I am proposing that we allow SO to reuse variants from the configurator.

Maybe it needs to be tri-state, as certainly for configurations with many attributes, it would be near impossible to find the correct variant through the pull down.

@PCatinean 
What do you think of a tri-state selection:

- Always create new configurations.
- Allow reuse of configurations.
- Allow configurations to be directly selected.

**Comment by PCatinean** [comment]
@yostashiro the reason for disabling configurable variants via dropdown is exactly what @richard-willdooit said "it would be near impossible to find the correct variant through the pull down". Also searching via typing will be very difficult to implement with many attributes and custom values => not a viable solution.

Regarding configurations I think there should never be a duplicate (this is what we've been trying to avoid all along).

I think the best design overall is to prevent duplicate products altogether and always re-use them. When it comes to custom values though it can be a bit more tricky but I always thought of moving them to the order line as they are usually specific to a customer order and are not standard.

While this might be debatable I started a PR to fix the duplicate product issue Yoshi mentioned without mixing in the custom values as Richard mentioned he uses in his implementation: https://github.com/pledra/odoo-product-configurator/pull/83

I still need to work on it a bit and add test cases but I always get interrupted. Reviews are welcome!

**Comment by PCatinean** [comment]
@richard-willdooit I just re-read your comment on a different PR and indeed the custom values should not be directly linked to sale.order as it can be independent (just in manufacturing).

So a different approach is needed for the long term.

**Comment by PCatinean** [comment]
@yostashiro this commit (https://github.com/pledra/odoo-product-configurator/commit/4def72254fdd6e5fe543b12f8dea573e1df5b005) should solve the issue.

I'm closing it for now, please feel free to re-open if you're still experiencing problems

**Comment by yostashiro** [comment]
@richard-willdooit @PCatinean thanks a lot.  I will check and report back if I notice any issues.
