### ISSUE TITLE
missing field attachment on sale order line attribute details prevents download

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#9]
If i compare to [pledra configurator demo](http://configurator-v9.pledra.com/web?debug=assets#id=25&view_type=form&model=sale.order&menu_id=176&action=244) my installation doesn't provide the field attachment_ids.
Probably that prevents me to download an attached file directly from the sale order line.

Field attachment visible in sale order line details:

<img width="1105" alt="bildschirmfoto 2017-01-12 um 13 55 23" src="https://cloud.githubusercontent.com/assets/8348598/21890861/fcc5ff66-d8cf-11e6-81b3-d8669b97ec69.png">

Missing field attachment (therefore no possibility to download the file).

<img width="1161" alt="bildschirmfoto 2017-01-12 um 13 59 33" src="https://cloud.githubusercontent.com/assets/8348598/21890879/1ea92054-d8d0-11e6-80be-8714ac70f3c2.png">

**Comment by PCatinean** [comment]
Solved by 7fb9c4af576791eaf4ca99d1fdbeebda4c319382

Thank you for reporting
